### Basic Makefile for MPI

CC = /usr/local/bin/mpicc
CFLAGS = -g -O0
LD = /usr/local/bin/mpicc
LDFLAGS = -g

PROGRAM = hello-mpi

all:    ${PROGRAM}.exe

${PROGRAM}.exe:         ${PROGRAM}.o
        ${LD} ${LDFLAGS} $< -o ${PROGRAM}.exe

${PROGRAM}.o:           ${PROGRAM}.c
        ${CC} ${CFLAGS} -c $< -o ${PROGRAM}.o

clean:
        rm -f ${PROGRAM}.o ${PROGRAM}.exe